//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMI_DataService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Details", Namespace="http://schemas.datacontract.org/2004/07/RMI_DataService")]
    [System.SerializableAttribute()]
    public partial class Details : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CostHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpanseHeadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Insurance_AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PR_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PanelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Sales_TaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cost {
            get {
                return this.CostField;
            }
            set {
                if ((object.ReferenceEquals(this.CostField, value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CostHead {
            get {
                return this.CostHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.CostHeadField, value) != true)) {
                    this.CostHeadField = value;
                    this.RaisePropertyChanged("CostHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpanseHead {
            get {
                return this.ExpanseHeadField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpanseHeadField, value) != true)) {
                    this.ExpanseHeadField = value;
                    this.RaisePropertyChanged("ExpanseHead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Insurance_Amount {
            get {
                return this.Insurance_AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.Insurance_AmountField, value) != true)) {
                    this.Insurance_AmountField = value;
                    this.RaisePropertyChanged("Insurance_Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PR_No {
            get {
                return this.PR_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.PR_NoField, value) != true)) {
                    this.PR_NoField = value;
                    this.RaisePropertyChanged("PR_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Panel {
            get {
                return this.PanelField;
            }
            set {
                if ((object.ReferenceEquals(this.PanelField, value) != true)) {
                    this.PanelField = value;
                    this.RaisePropertyChanged("Panel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sales_Tax {
            get {
                return this.Sales_TaxField;
            }
            set {
                if ((object.ReferenceEquals(this.Sales_TaxField, value) != true)) {
                    this.Sales_TaxField = value;
                    this.RaisePropertyChanged("Sales_Tax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceDetails {
            get {
                return this.ServiceDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceDetailsField, value) != true)) {
                    this.ServiceDetailsField = value;
                    this.RaisePropertyChanged("ServiceDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRMIDataService")]
    public interface IRMIDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRMIDataService/GetData", ReplyAction="http://tempuri.org/IRMIDataService/GetDataResponse")]
        RMI_DataService.ServiceReference1.Details[] GetData(string flag);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRMIDataServiceChannel : RMI_DataService.ServiceReference1.IRMIDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RMIDataServiceClient : System.ServiceModel.ClientBase<RMI_DataService.ServiceReference1.IRMIDataService>, RMI_DataService.ServiceReference1.IRMIDataService {
        
        public RMIDataServiceClient() {
        }
        
        public RMIDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RMIDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RMIDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RMIDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RMI_DataService.ServiceReference1.Details[] GetData(string flag) {
            return base.Channel.GetData(flag);
        }
    }
}
